### ISSUE TITLE
Any way to install it without Nix dependency?

### ISSUE THREAD

**Issue by JerryGreen** [Shopify/asls#46]
Pls

**Comment by saulecabrera** [comment]
Right now there isn't but we are working on bringing better support for Windows.

**Comment by JerryGreen** [comment]
Sounds good!

**Comment by saulecabrera** [comment]
@JerryGreen I've published https://github.com/Shopify/vscode-as/releases/tag/v0.4.0 which bundles the language server binary, so there's no need to install the binary prior to installing the VSCode extension. Windows is supported only via WSL.
